name: Create terraform plan

on:
  push:
    branches:
      - workflow

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for Terraform config
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: ./